package com.oopproject.form.models.User;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;
import org.springframework.format.annotation.DateTimeFormat;

// import jakarta.validation.constraints.Email;
// import jakarta.validation.constraints.NotBlank;
// import jakarta.validation.constraints.Size;

@Document(collection = "User")
public class User {
    @Id
    private String id;
    // id autogenerated by mongodb. I did not make a setter for this since Id should
    // never be changed? can we do this with lombok? will there be risk of
    // accidentlly changing the id? idk. something to think about

    // @NotBlank
    // @Size(max = 20)
    private String username;

    // @NotBlank
    // @Size(max = 50)
    // @Email
    private String email;

    // @NotBlank
    // @Size(max = 120)
    private String password;

    private Roles role;

    private String country;

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date created_at;

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date deleted_at;
    // store timestamp when user is created in the ISO format
    @DocumentReference(lazy = true)
    private User created_by;
    // store ObjectId of user that creates the user. must be able to get the current
    // user object first then pass that into the userService

    public User() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public User getCreated_by() {
        return created_by;
    }

    public void setCreated_by(User created_by) {
        this.created_by = created_by;
    }

    public Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Roles getRole() {
        return role;
    }

    public void setRole(Roles role) {
        this.role = role;
    }

    public Date getDeleted_at() {
        return deleted_at;
    }

    public void setDeleted_at(Date deleted_at) {
        this.deleted_at = deleted_at;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", username=" + username + ", email=" + email + ", password=" + password + ", role="
                + role + ", created_at=" + created_at + ", created_by=" + created_by + "]";
    }

}
